name: proto
description: Socfony protobuf library, shared between the server and the client.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  grpc: ^3.0.2

dev_dependencies:
  lints: ^1.0.0
